name: project_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  pinput: ^3.0.1
  intl: ^0.20.2
  firebase_core: ^3.12.1
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  cloud_firestore: ^5.6.5
  google_maps_flutter: ^2.12.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  ola_maps: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

#  assets:
#
#  fonts:
#    - family: Pacifico
#      fonts:
#        - asset: assets/fonts/Pacifico-Regular.ttf
