name: project_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  pinput: ^3.0.1
  intl: ^0.20.2
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  flutter_map: ^8.1.1
  url_launcher: ^6.3.1
  geocoding: ^3.0.0
  geolocator: ^13.0.3
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.5.3
  firebase_auth: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

indexes:
- collection: transaction
  fields:
  - name: partnerId
    order: ASCENDING
  - name: date
    order: DESCENDING
#  assets:
#
#  fonts:
#    - family: Pacifico
#      fonts:
#        - asset: assets/fonts/Pacifico-Regular.ttf
