// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoFCY9EfHfR4gjRU_znqpdb3t8A4Zd9Ig',
    appId: '1:467358761446:web:12135bfcae5a25369cd627',
    messagingSenderId: '467358761446',
    projectId: 'deligo-62e14',
    authDomain: 'deligo-62e14.firebaseapp.com',
    storageBucket: 'deligo-62e14.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvq7FT22O1XH4okU56_46P4_47BD6fTUw',
    appId: '1:467358761446:android:0e5bc64a120aa47e9cd627',
    messagingSenderId: '467358761446',
    projectId: 'deligo-62e14',
    storageBucket: 'deligo-62e14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL94cJhGlKYM5Pq08bCBJWd_HHhPdJzmE',
    appId: '1:467358761446:ios:b7ea9e94add74dd09cd627',
    messagingSenderId: '467358761446',
    projectId: 'deligo-62e14',
    storageBucket: 'deligo-62e14.firebasestorage.app',
    iosBundleId: 'com.example.partner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL94cJhGlKYM5Pq08bCBJWd_HHhPdJzmE',
    appId: '1:467358761446:ios:b7ea9e94add74dd09cd627',
    messagingSenderId: '467358761446',
    projectId: 'deligo-62e14',
    storageBucket: 'deligo-62e14.firebasestorage.app',
    iosBundleId: 'com.example.partner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoFCY9EfHfR4gjRU_znqpdb3t8A4Zd9Ig',
    appId: '1:467358761446:web:79eac9c6ec7a89db9cd627',
    messagingSenderId: '467358761446',
    projectId: 'deligo-62e14',
    authDomain: 'deligo-62e14.firebaseapp.com',
    storageBucket: 'deligo-62e14.firebasestorage.app',
  );
}
